name: pretty-rest

on:
  push:
    branches: [master]

jobs:
  init:
    name: Checkout and setup node
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
  build-common:
    name: Build and link common package
    runs-on: self-hosted
    needs: [init]
    steps:
      - run: npm install && npm run build && npm link
        working-directory: ./src/packages/common
  build-resolver:
    name: Build resolver package
    runs-on: self-hosted
    needs: [init]
    steps:
      - run: npm install && npm run build
        working-directory: ./src/packages/resolver
  build-express:
    name: Build and link express package
    runs-on: self-hosted
    needs: [init]
    steps:
      - run: npm install && npm run build && npm link
        working-directory: ./src/packages/express
  build-fetch:
    name: Build and link fetch package
    runs-on: self-hosted
    needs: [init]
    steps:
      - run: npm install && npm run build && npm link
        working-directory: ./src/packages/fetch
  build:
    name: Link root package
    runs-on: self-hosted
    needs: [init]
    steps:
      - run: npm install && npm link
